# Generated by Django 6.0.6 on 2026-06-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_parentstudentmapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentprofile',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='parentstudentmapping',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'ordering': ['-id']},
        ),
    ]
