# Generated by Django 6.0.6 on 2026-07-02 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_parentprofile_profile_picture_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imei_number', models.CharField(help_text='Unique IMEI number of the device', max_length=20, unique=True)),
                ('device_type', models.CharField(choices=[('phone', 'Phone'), ('tablet', 'Tablet'), ('smartwatch', 'Smartwatch'), ('other', 'Other')], default='phone', max_length=20)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('last_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='profiles.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Device',
                'verbose_name_plural': 'Student Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentLocationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy', models.FloatField(blank=True, help_text='Accuracy in meters', null=True)),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in m/s', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Heading in degrees', null=True)),
                ('location_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='profiles.studentdevice')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='profiles.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Location History',
                'verbose_name_plural': 'Student Location Histories',
                'ordering': ['-location_time'],
            },
        ),
        migrations.AddIndex(
            model_name='studentdevice',
            index=models.Index(fields=['imei_number'], name='profiles_st_imei_nu_48e079_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdevice',
            index=models.Index(fields=['student', 'is_active'], name='profiles_st_student_ba9161_idx'),
        ),
        migrations.AddIndex(
            model_name='studentlocationhistory',
            index=models.Index(fields=['student', 'location_time'], name='profiles_st_student_44eec7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentlocationhistory',
            index=models.Index(fields=['device', 'location_time'], name='profiles_st_device__eec978_idx'),
        ),
    ]
