# Generated by Django 6.0.6 on 2026-06-16 02:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Unique identifier (English phrase)', max_length=255)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], max_length=10)),
                ('text', models.TextField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
            ],
            options={
                'ordering': ['key', 'language_code'],
                'unique_together': {('school', 'key', 'language_code')},
            },
        ),
    ]
