# Generated by Django 6.0.6 on 2026-06-16 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0002_translation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
