# Generated by Django 6.0.6 on 2026-06-29 09:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0005_grievance'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('working_days', models.JSONField(default=list, help_text="List of working days (e.g., ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'])")),
                ('periods_per_day', models.IntegerField(default=8, help_text='Number of periods in a day')),
                ('period_duration', models.IntegerField(default=45, help_text='Duration of each period in minutes')),
                ('school_start_time', models.TimeField(default='08:00:00', help_text='School start time')),
                ('school_end_time', models.TimeField(default='15:00:00', help_text='School end time')),
                ('break_duration', models.IntegerField(default=15, help_text='Short break duration in minutes')),
                ('lunch_duration', models.IntegerField(default=30, help_text='Lunch break duration in minutes')),
                ('break_start_after_period', models.IntegerField(default=2, help_text='Period number after which break occurs')),
                ('lunch_start_after_period', models.IntegerField(default=4, help_text='Period number after which lunch occurs')),
                ('max_same_subject_per_day', models.IntegerField(default=2, help_text='Maximum periods of same subject per day')),
                ('max_same_subject_per_week', models.IntegerField(default=6, help_text='Maximum periods of same subject per week')),
                ('auto_generate', models.BooleanField(default=False, help_text='Enable auto-generation of timetable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Timetable Settings',
            },
        ),
        migrations.CreateModel(
            name='TimetableConfigHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(help_text="Dictionary of changes made (field_name: {'old': value, 'new': value})")),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('timetable_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='school_admin.timetablesettings')),
            ],
            options={
                'verbose_name_plural': 'Timetable Settings History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='timetablesettings',
            constraint=models.UniqueConstraint(fields=('school',), name='unique_timetable_settings_per_school'),
        ),
    ]
