# Generated by Django 6.0.6 on 2026-06-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0006_timetablesettings_timetableconfighistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetablesettings',
            name='break_duration',
        ),
        migrations.RemoveField(
            model_name='timetablesettings',
            name='break_start_after_period',
        ),
    ]
