# Generated by Django 6.0.6 on 2026-06-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0007_remove_timetablesettings_break_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablesettings',
            name='lunch_duration',
            field=models.IntegerField(help_text='Lunch break duration in minutes'),
        ),
        migrations.AlterField(
            model_name='timetablesettings',
            name='lunch_start_after_period',
            field=models.IntegerField(help_text='Period number after which lunch occurs'),
        ),
        migrations.AlterField(
            model_name='timetablesettings',
            name='max_same_subject_per_day',
            field=models.IntegerField(help_text='Maximum periods of same subject per day'),
        ),
        migrations.AlterField(
            model_name='timetablesettings',
            name='max_same_subject_per_week',
            field=models.IntegerField(help_text='Maximum periods of same subject per week'),
        ),
        migrations.AlterField(
            model_name='timetablesettings',
            name='period_duration',
            field=models.IntegerField(help_text='Duration of each period in minutes'),
        ),
        migrations.AlterField(
            model_name='timetablesettings',
            name='periods_per_day',
            field=models.IntegerField(help_text='Number of periods in a day'),
        ),
        migrations.AlterField(
            model_name='timetablesettings',
            name='school_end_time',
            field=models.TimeField(help_text='School end time'),
        ),
        migrations.AlterField(
            model_name='timetablesettings',
            name='school_start_time',
            field=models.TimeField(help_text='School start time'),
        ),
        migrations.AlterField(
            model_name='timetablesettings',
            name='working_days',
            field=models.JSONField(help_text="List of working days (e.g., ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'])"),
        ),
    ]
