# Generated by Django 6.0.6 on 2026-06-29 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_savedaicontent'),
        ('school_admin', '0008_alter_timetablesettings_lunch_duration_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('target_audience', models.CharField(choices=[('all', 'All'), ('students', 'Students'), ('teachers', 'Teachers'), ('parents', 'Parents')], db_index=True, default='all', max_length=20)),
                ('attachment_key', models.CharField(blank=True, help_text='R2 object key for the attached file.', max_length=500, null=True)),
                ('attachment_name', models.CharField(blank=True, help_text='Original filename shown to recipients.', max_length=255, null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Unpublish to hide from recipients without deleting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circulars_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('target_class_levels', models.ManyToManyField(blank=True, help_text='Leave empty to target every class in the school.', related_name='circulars', to='academics.classlevel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
