# Generated by Django 6.0.6 on 2026-06-29 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='leave_manag_school__5e1a71_idx',
            old_name='leave_man_l_school__b1a5c1_idx',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='leave_manag_student_9d5900_idx',
            old_name='leave_man_l_student_4f2b29_idx',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='leave_manag_teacher_b546b1_idx',
            old_name='leave_man_l_teacher_7d3a9e_idx',
        ),
    ]
