# Generated by Django 6.0.6 on 2026-06-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_pendingsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmission',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='submissions/'),
        ),
    ]
